{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.stringData }}
stringData:
{{ toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.secret.data }}
data:
{{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
