apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-preview" .Values.userService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.userService.name }}
  ports:
    - port: {{ .Values.userService.servicePort }}
      targetPort: {{ .Values.userService.serviceTargetPort }}
  type: {{ .Values.userService.serviceType }}
{{- end }}
