apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  TASK_SERVICE_URL: "http://task-service:3003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3005"
  ALLOWED_ORIGINS: "*"
  JWT_EXPIRES_IN: "7d"
  NODE_ENV: "development"
